image: node

pipelines:
  pull-requests:
    "**":
      - step:
          caches:
            - node
          script:
            - npm install
            - npm install -g firebase-tools
            - npx nx build public-web --configuration development
            - firebase hosting:channel:deploy "preview-$BITBUCKET_PR_ID" --only dev --token "$FIREBASE_TOKEN"
            - firebase deploy --only firestore:rules
  branches:
    dev:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm install -g firebase-tools
            - cd functions
            - npm install
            - cd ../
            - npx nx build public-web --configuration development
            - firebase deploy --only hosting:dev --token "$FIREBASE_TOKEN"
            # - firebase deploy --only functions
            - firebase deploy --only firestore:rules
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm install -g firebase-tools
            - cd functions
            - npm install
            - cd ../
            - npx nx build public-web --configuration qa --aot
            - firebase deploy --only hosting:qa --token "$FIREBASE_TOKEN"
            # - firebase deploy --only functions
            - firebase deploy --only firestore:rules
  tags:
    release-*:
      - step:
          script:
            - npm install
            - npm install -g firebase-tools
            - cd functions
            - npm install
            - cd ../
            - npx nx build public --configuration production --aot
            - firebase deploy --only hosting:prod --token "$FIREBASE_TOKEN"
            # - firebase deploy --only functions
            - firebase deploy --only firestore:rules
